# docker-compose.yaml
version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "3306:3306"
    volumes:
      # DB 데이터 저장 디렉터리
      - ./data:/var/lib/mysql
      # 설정 파일 저장될 위치
      - ./config:/etc/mysql/conf.d
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    env_file: .env
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  user-service:
    container_name: user-service
    image: user-service:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "64412:64412"
    depends_on:
      - config-server
      - discovery-server
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  order-service:
    container_name: order-service
    image: order-service:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "54412:54412"
    depends_on:
      - config-server
      - discovery-server
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  config-server:
    container_name: config-server
    image: config-server:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "8888:8888"
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    env_file: .env
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  discovery-server:
    container_name: discovery-server
    image: discovery-server:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "8761:8761"
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    env_file: .env
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  api-gateway-service:
    container_name: api-gateway-service
    image: api-gateway-service:latest
    restart: always
    # 환경에 따라 변경
    ports:
      - "8000:8000"
    depends_on:
      - discovery-server
    environment:
      # 컨테이너 내의 시스템 타임존을 우리나라에 맞게 설정합니다.
      - "TZ=Asia/Seoul"
    env_file: .env
    command:
      # 위 명령어를 사용하지 않으면, 일부 설정이 latin으로 설정됩니다.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  default:
    driver: bridge