server:
  port: 54412

spring:
  application:
    name: order-service
  profiles:
    active: local
  config:
    import: configserver:http://config-server:8888
  cloud:
    config: # Ex) `http://localhost:8888/config/local`
      name: config # config name
      profile: local # config profile

management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh

eureka:
  instance:
    instance-id: order-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka