server:
  port: 54412

spring:
  application:
    name: order-service
  profiles:
    active: local
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config: # Ex) `http://localhost:8088/config/test`
      name: config # config name
      profile: local # config profile

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  instance:
    instance-id: order-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka